name: 'Terraform Deploy Azure VM'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VERSION: '1.6.6'
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  deploy:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Inject SSH Key into tfvars (heredoc style)'
        run: |
          cat <<EOF > override.tfvars
          admin_ssh_public_key = <<EOKEY
          ${{ env.SSH_PUBLIC_KEY }}
          EOKEY
          EOF

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan -var-file="override.tfvars" -out=tfplan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
